Repository NightzWatch/ThRead, pull requests merged in 2018-06, with the labels that each got.

#27 all the styling for native base components in one place
  thread/App.js
  thread/native-base-theme/components/Badge.js
  thread/native-base-theme/components/Body.js
  thread/native-base-theme/components/Button.js
  thread/native-base-theme/components/Card.js
  thread/native-base-theme/components/CardItem.js
  thread/native-base-theme/components/CheckBox.js
  thread/native-base-theme/components/Container.js
  thread/native-base-theme/components/Content.js
  thread/native-base-theme/components/Fab.js
  thread/native-base-theme/components/Footer.js
  thread/native-base-theme/components/FooterTab.js
  thread/native-base-theme/components/Form.js
  thread/native-base-theme/components/H1.js
  thread/native-base-theme/components/H2.js
  thread/native-base-theme/components/H3.js
  thread/native-base-theme/components/Header.js
  thread/native-base-theme/components/Icon.js
  thread/native-base-theme/components/Input.js
  thread/native-base-theme/components/InputGroup.js
  thread/native-base-theme/components/Item.js
  thread/native-base-theme/components/Label.js
  thread/native-base-theme/components/Left.js
  thread/native-base-theme/components/ListItem.js
  thread/native-base-theme/components/Picker.android.js
  thread/native-base-theme/components/Picker.ios.js
  thread/native-base-theme/components/Picker.js
  thread/native-base-theme/components/Radio.js
  thread/native-base-theme/components/Right.js
  thread/native-base-theme/components/Segment.js
  thread/native-base-theme/components/Separator.js
  thread/native-base-theme/components/Spinner.js
  thread/native-base-theme/components/Subtitle.js
  thread/native-base-theme/components/SwipeRow.js
  thread/native-base-theme/components/Switch.js
  thread/native-base-theme/components/Tab.js
  thread/native-base-theme/components/TabBar.js
  thread/native-base-theme/components/TabContainer.js
  thread/native-base-theme/components/TabHeading.js
  thread/native-base-theme/components/Text.js
  thread/native-base-theme/components/Textarea.js
  thread/native-base-theme/components/Thumbnail.js
  thread/native-base-theme/components/Title.js
  thread/native-base-theme/components/Toast.js
  thread/native-base-theme/components/View.js
  thread/native-base-theme/components/index.js
  thread/native-base-theme/variables/commonColor.js
  thread/native-base-theme/variables/material.js
  thread/native-base-theme/variables/platform.js
Labels: For Review

#22 we can now privately send messages woop!!!
  thread/.travis.yml
  thread/__tests__/App.test.js
  thread/package-lock.json
  thread/package.json
  thread/src/Router.js
  thread/src/actions/AuthActions.js
  thread/src/actions/ContactActions.js
  thread/src/actions/types.js
  thread/src/components/Common/CentredContent.js
  thread/src/components/Common/ContentSpinner.js
  thread/src/components/Common/index.js
  thread/src/components/ContactTabs.js
  thread/src/components/Contacts.js
  thread/src/components/Contacts/AddContactForm.js
  thread/src/components/Contacts/ContactList.js
  thread/src/components/Contacts/ContactListItem.js
  thread/src/components/Contacts/RequestsReceived.js
  thread/src/components/Contacts/RequestsSent.js
  thread/src/components/Contacts/Tabs.js
  thread/src/components/Messenger/AddMembersForm.js
  thread/src/components/RegisterForm.js
  thread/src/components/RequestsSent.js
  thread/src/components/ResetPasswordForm.js
  thread/src/components/Threads.js
  thread/src/components/common/CommonButton.js
  thread/src/reducers/ContactsReducer.js
  thread/src/reducers/RequestsReceivedReducer.js
  thread/src/reducers/RequestsSentReducer.js
  thread/src/reducers/__tests__/ContactsReducer.test.js
  thread/src/reducers/__tests__/RequestsReceivedReducer.test.js
  thread/src/reducers/__tests__/RequestsSentReducer.test.js
Labels: UI

#31 Forgot password
  thread/App.js
  thread/native-base-theme/variables/ThRead.js
  thread/package.json
  thread/src/Router.js
  thread/src/components/Common/CommonContainer.js
  thread/src/components/Common/CommonField.js
  thread/src/components/Common/LoadingButton.js
  thread/src/components/Common/index.js
  thread/src/components/RegisterForm.js
  thread/src/components/ResetPasswordForm.js
  thread/yarn.lock
Labels: UX

#28 We can now stay logged in after closing app
  thread/App.js
  thread/src/actions/AuthActions.js
  thread/src/actions/RegisterActions.js
  thread/src/components/LoginForm.js
  thread/src/reducers/AuthReducer.js
Labels: For Review
