Repository NightzWatch/ThRead, pull requests merged in 2018-05, with the labels that each got.

#16 Refactor date format function to oneline
  thread/src/components/Threads.js
Labels: For Review, Hygiene

#14 fixed duplicate threads
  thread/src/actions/ChatRoomsActions.js
  thread/src/actions/index.js
  thread/src/components/CreateTreadForm.js
Labels: bug

#19 footer looks much better
  thread/src/Router.js
  thread/src/components/FooterTabs.js
Labels: For Review, UI

#18 Refactor methods to be stateless where possible and create a CommonButton
  thread/src/Router.js
  thread/src/components/AddContactButton.js
  thread/src/components/ContactTabs.js
  thread/src/components/CreateThreadButton.js
  thread/src/components/Messenger/CloseButton.js
  thread/src/components/Messenger/InfoButton.js
  thread/src/components/PrivacyPolicy.js
  thread/src/components/TermsAndConditions.js
  thread/src/components/Threads.js
  thread/src/components/common/CommonButton.js
Labels: For Review, Hygiene

#21 Branchy mc branchface
  thread/src/components/Messenger/Bubble.js
  thread/src/components/Messenger/Message.js
Labels: bug
